USE impostor_party;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS migration_2026_host_tasks (
    migration_key VARCHAR(64) NOT NULL PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET @sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE players ADD COLUMN user_id INT NULL AFTER id',
        'SELECT 1')
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'players'
      AND column_name = 'user_id'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE players ADD CONSTRAINT fk_players_user FOREIGN KEY (user_id) REFERENCES users(id)',
        'SELECT 1')
    FROM information_schema.key_column_usage
    WHERE constraint_schema = DATABASE()
      AND table_name = 'players'
      AND column_name = 'user_id'
      AND referenced_table_name = 'users'
      AND referenced_column_name = 'id'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE players ADD UNIQUE KEY uq_players_room_user (room_id, user_id)',
        'SELECT 1')
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'players'
      AND index_name = 'uq_players_room_user'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE players ADD UNIQUE KEY uq_players_session_token (session_token)',
        'SELECT 1')
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'players'
      AND index_name = 'uq_players_session_token'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE tasks ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE AFTER is_for_impostor',
        'SELECT 1')
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'tasks'
      AND column_name = 'active'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE player_tasks ADD COLUMN position INT NULL AFTER task_id',
        'SELECT 1')
    FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = 'player_tasks'
      AND column_name = 'position'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

UPDATE player_tasks
SET position = id
WHERE position IS NULL;

ALTER TABLE player_tasks
    MODIFY COLUMN position INT NOT NULL DEFAULT 0;

DROP TEMPORARY TABLE IF EXISTS task_duplicate_map;
CREATE TEMPORARY TABLE task_duplicate_map (
    duplicate_id INT NOT NULL PRIMARY KEY,
    canonical_id INT NOT NULL
);
INSERT INTO task_duplicate_map (duplicate_id, canonical_id)
SELECT t.id, canonical.id
FROM tasks t
JOIN (
    SELECT challenge_type, description, MIN(id) AS id
    FROM tasks
    GROUP BY challenge_type, description
) canonical
  ON canonical.challenge_type = t.challenge_type
 AND canonical.description = t.description
WHERE t.id <> canonical.id;
UPDATE player_tasks pt
JOIN task_duplicate_map duplicates ON duplicates.duplicate_id = pt.task_id
SET pt.task_id = duplicates.canonical_id;
DELETE t
FROM tasks t
JOIN task_duplicate_map duplicates ON duplicates.duplicate_id = t.id;
DROP TEMPORARY TABLE task_duplicate_map;

SET @sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE tasks ADD UNIQUE KEY uq_tasks_challenge_description (challenge_type, description)',
        'SELECT 1')
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'tasks'
      AND index_name = 'uq_tasks_challenge_description'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

DELETE older
FROM words older
INNER JOIN words newer
    ON older.challenge_type = newer.challenge_type
   AND older.word = newer.word
   AND older.id > newer.id;

SET @sql = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE words ADD UNIQUE KEY uq_words_challenge_word (challenge_type, word)',
        'SELECT 1')
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'words'
      AND index_name = 'uq_words_challenge_word'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

INSERT INTO words (word, challenge_type) VALUES
('Playa', 'normales'),
('Pizza', 'normales'),
('Bicicleta', 'normales'),
('Cine', 'normales'),
('Guitarra', 'normales'),
('Piscina', 'amigos'),
('Barbacoa', 'amigos'),
('Karaoke', 'amigos'),
('Excursion', 'amigos'),
('Videojuego', 'amigos'),
('Masaje', 'picantes'),
('Baile lento', 'picantes'),
('Perfume', 'picantes'),
('Susurro', 'picantes'),
('Cena a la luz de las velas', 'picantes'),
('Cotilleo', 'salseo'),
('Ex pareja', 'salseo'),
('Secreto', 'salseo'),
('Rumor', 'salseo'),
('Indirecta', 'salseo'),
('Salto en paracaidas', 'extremos'),
('Comida picante', 'extremos'),
('Karaoke a gritos', 'extremos'),
('Reto de frio', 'extremos'),
('Bano en agua helada', 'extremos')
ON DUPLICATE KEY UPDATE word = VALUES(word);

SET @migration_applied = (
    SELECT COUNT(*) FROM migration_2026_host_tasks WHERE migration_key = '2026_host_tasks'
);
SET @sql = IF(@migration_applied = 0,
    'UPDATE rooms SET status = ''FINISHED'' WHERE status = ''LOBBY'' OR (status = ''IN_PROGRESS'' AND end_time IS NULL)',
    'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(@migration_applied = 0,
    'UPDATE tasks SET active = FALSE',
    'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

INSERT INTO tasks (description, challenge_type, is_for_impostor, active) VALUES
('Prepara un café solo', 'normales', FALSE, TRUE),
('Prepara un té', 'normales', FALSE, TRUE),
('Prepara un chocolate caliente', 'normales', FALSE, TRUE),
('Prepara una infusión', 'normales', FALSE, TRUE),
('Prepara un vaso de agua con hielo', 'normales', FALSE, TRUE),
('Ordena un escritorio', 'normales', FALSE, TRUE),
('Ordena una mesa', 'normales', FALSE, TRUE),
('Ordena una mochila', 'normales', FALSE, TRUE),
('Ordena un armario', 'normales', FALSE, TRUE),
('Ordena una estantería', 'normales', FALSE, TRUE),
('Cuenta una anécdota de viaje', 'normales', FALSE, TRUE),
('Cuenta un recuerdo de la infancia', 'normales', FALSE, TRUE),
('Cuenta una anécdota del trabajo', 'normales', FALSE, TRUE),
('Cuenta algo que pasó ayer', 'normales', FALSE, TRUE),
('Cuenta una historia de amistad', 'normales', FALSE, TRUE),
('Comparte una recomendación de música', 'normales', FALSE, TRUE),
('Comparte un dato curioso', 'normales', FALSE, TRUE),
('Comparte una receta sencilla', 'normales', FALSE, TRUE),
('Comparte una foto bonita', 'normales', FALSE, TRUE),
('Comparte un consejo práctico', 'normales', FALSE, TRUE),
('Limpia una mesa', 'normales', FALSE, TRUE),
('Limpia un paño de cocina', 'normales', FALSE, TRUE),
('Limpia una ventana', 'normales', FALSE, TRUE),
('Limpia un teclado', 'normales', FALSE, TRUE),
('Limpia el baño', 'normales', FALSE, TRUE),
('Elige una película', 'normales', FALSE, TRUE),
('Elige una melodía', 'normales', FALSE, TRUE),
('Elige un juego de mesa', 'normales', FALSE, TRUE),
('Elige un libro', 'normales', FALSE, TRUE),
('Elige una serie', 'normales', FALSE, TRUE),
('Ayuda a alguien a guardar sus cosas', 'normales', FALSE, TRUE),
('Ayuda a alguien a encontrar un objeto perdido', 'normales', FALSE, TRUE),
('Ayuda a alguien a preparar una merienda', 'normales', FALSE, TRUE),
('Ayuda a alguien a ordenar una habitación', 'normales', FALSE, TRUE),
('Ayuda a alguien a montar una mesa', 'normales', FALSE, TRUE),
('Escribe una nota de agradecimiento', 'normales', FALSE, TRUE),
('Escribe una lista de compras', 'normales', FALSE, TRUE),
('Escribe un mensaje amable', 'normales', FALSE, TRUE),
('Escribe una agenda breve', 'normales', FALSE, TRUE),
('Escribe una receta improvisada', 'normales', FALSE, TRUE),
('Guarda las llaves en un lugar fijo', 'normales', FALSE, TRUE),
('Guarda la ropa limpia', 'normales', FALSE, TRUE),
('Guarda los papeles en una carpeta', 'normales', FALSE, TRUE),
('Guarda los juguetes en una caja', 'normales', FALSE, TRUE),
('Guarda el móvil lejos de la mesa', 'normales', FALSE, TRUE),
('Prepara una ensalada', 'normales', FALSE, TRUE),
('Prepara un sándwich', 'normales', FALSE, TRUE),
('Prepara una tostada', 'normales', FALSE, TRUE),
('Prepara una sopa', 'normales', FALSE, TRUE),
('Prepara un plato de fruta', 'normales', FALSE, TRUE),
('Pon un recordatorio', 'normales', FALSE, TRUE),
('Pon un poco de música', 'normales', FALSE, TRUE),
('Pon la mesa', 'normales', FALSE, TRUE),
('Pon un vídeo corto', 'normales', FALSE, TRUE),
('Pon un vaso de agua', 'normales', FALSE, TRUE),
('Abre una ventana', 'normales', FALSE, TRUE),
('Abre un mapa', 'normales', FALSE, TRUE),
('Abre un libro', 'normales', FALSE, TRUE),
('Abre un mensaje', 'normales', FALSE, TRUE),
('Abre una aplicación nueva', 'normales', FALSE, TRUE),
('Revisa tu agenda', 'normales', FALSE, TRUE),
('Revisa tu cartera', 'normales', FALSE, TRUE),
('Revisa la lista de la compra', 'normales', FALSE, TRUE),
('Entrad al baño y salid en cinco segundos', 'normales', FALSE, TRUE),
('Revisa las notificaciones del móvil', 'normales', FALSE, TRUE),
('Saluda a la persona que llegue primero', 'normales', FALSE, TRUE),
('Saluda a alguien en el ascensor', 'normales', FALSE, TRUE),
('Saluda a un vecino', 'normales', FALSE, TRUE),
('Saluda al grupo', 'normales', FALSE, TRUE),
('Saluda a quien esté a tu lado', 'normales', FALSE, TRUE),
('Muestra un objeto pequeño', 'normales', FALSE, TRUE),
('Muestra una foto antigua', 'normales', FALSE, TRUE),
('Muestra una colección de monedas', 'normales', FALSE, TRUE),
('Muestra una planta', 'normales', FALSE, TRUE),
('Muestra una receta', 'normales', FALSE, TRUE),
('Cruza las piernas y mantén la postura', 'normales', FALSE, TRUE),
('Camina hasta la tienda', 'normales', FALSE, TRUE),
('Camina alrededor del parque', 'normales', FALSE, TRUE),
('Camina por una calle nueva', 'normales', FALSE, TRUE),
('Camina hacia el centro', 'normales', FALSE, TRUE),
('Lee unas páginas', 'normales', FALSE, TRUE),
('Lee un artículo breve', 'normales', FALSE, TRUE),
('Lee las instrucciones', 'normales', FALSE, TRUE),
('Lee las noticias', 'normales', FALSE, TRUE),
('Lee una biografía', 'normales', FALSE, TRUE),
('Separa los reciclables', 'normales', FALSE, TRUE),
('Separa la ropa por colores', 'normales', FALSE, TRUE),
('Separa los papeles', 'normales', FALSE, TRUE),
('Separa los objetos pequeños', 'normales', FALSE, TRUE),
('Separa las botellas', 'normales', FALSE, TRUE),
('Extiende la ropa limpia', 'normales', FALSE, TRUE),
('Extiende las toallas húmedas', 'normales', FALSE, TRUE),
('Extiende un par de calcetines', 'normales', FALSE, TRUE),
('Extiende una sábana', 'normales', FALSE, TRUE),
('Extiende un delantal', 'normales', FALSE, TRUE),
('Escucha una canción', 'normales', FALSE, TRUE),
('Escucha un sonido de la naturaleza', 'normales', FALSE, TRUE),
('Escucha un podcast breve', 'normales', FALSE, TRUE),
('Escucha una conversación', 'normales', FALSE, TRUE),
('Escucha un instrumento', 'normales', FALSE, TRUE),
('Corta fruta para compartir', 'normales', FALSE, TRUE),
('Corta el pan', 'normales', FALSE, TRUE),
('Corta una etiqueta', 'normales', FALSE, TRUE),
('Corta un pedazo de papel', 'normales', FALSE, TRUE),
('Corta una hoja grande', 'normales', FALSE, TRUE),
('Sirve agua', 'normales', FALSE, TRUE),
('Sirve la merienda', 'normales', FALSE, TRUE),
('Sirve un plato', 'normales', FALSE, TRUE),
('Sirve una porción', 'normales', FALSE, TRUE),
('Sirve una taza', 'normales', FALSE, TRUE),
('Toma una foto del cielo', 'normales', FALSE, TRUE),
('Di los números del uno al cinco en voz alta', 'normales', FALSE, TRUE),
('Toma una pausa breve', 'normales', FALSE, TRUE),
('Toma un billete de transporte', 'normales', FALSE, TRUE),
('Toma una nota de humor', 'normales', FALSE, TRUE),
('Cierra la puerta', 'normales', FALSE, TRUE),
('Cierra la ventana', 'normales', FALSE, TRUE),
('Cierra la tapa de un bote', 'normales', FALSE, TRUE),
('Cierra el libro', 'normales', FALSE, TRUE),
('Cierra la caja', 'normales', FALSE, TRUE),
('Crea un horario', 'normales', FALSE, TRUE),
('Crea una lista de ideas', 'normales', FALSE, TRUE),
('Crea una playlist', 'normales', FALSE, TRUE),
('Crea un dibujo sencillo', 'normales', FALSE, TRUE),
('Crea un plan de paseo', 'normales', FALSE, TRUE),
('Cambia la bombilla', 'normales', FALSE, TRUE),
('Cambia la toalla', 'normales', FALSE, TRUE),
('Cambia el cepillo de dientes', 'normales', FALSE, TRUE),
('Cambia la bolsa de la basura', 'normales', FALSE, TRUE),
('Cambia el décor de la sala', 'normales', FALSE, TRUE),
('Mueve un mueble pequeño', 'normales', FALSE, TRUE),
('Mueve una silla', 'normales', FALSE, TRUE),
('Mueve una caja', 'normales', FALSE, TRUE),
('Mueve un objeto pequeño', 'normales', FALSE, TRUE),
('Mueve una planta', 'normales', FALSE, TRUE),
('Pide una aclaración', 'normales', FALSE, TRUE),
('Pide un vaso de agua', 'normales', FALSE, TRUE),
('Pide una receta fácil', 'normales', FALSE, TRUE),
('Pide una mano para un proyecto', 'normales', FALSE, TRUE),
('Pide una bombilla de repuesto', 'normales', FALSE, TRUE),
('Ofrece un asiento', 'normales', FALSE, TRUE),
('Ofrece ayuda con una bolsa', 'normales', FALSE, TRUE),
('Ofrece un aperitivo sencillo', 'normales', FALSE, TRUE),
('Ofrece una sonrisa', 'normales', FALSE, TRUE),
('Ofrece una copia de tus notas', 'normales', FALSE, TRUE),
('Anota la hora de una reunión', 'normales', FALSE, TRUE),
('Anota un número de teléfono', 'normales', FALSE, TRUE),
('Anota una idea para luego', 'normales', FALSE, TRUE),
('Anota una compra pendiente', 'normales', FALSE, TRUE),
('Anota un detalle de la agenda', 'normales', FALSE, TRUE),
('Prepara un mojito sin alcohol', 'amigos', FALSE, TRUE),
('Prepara una sangria suave', 'amigos', FALSE, TRUE),
('Prepara una limonada', 'amigos', FALSE, TRUE),
('Prepara un té frío', 'amigos', FALSE, TRUE),
('Prepara un café con canela', 'amigos', FALSE, TRUE),
('Sirve una ronda de bebidas', 'amigos', FALSE, TRUE),
('Sirve un aperitivo', 'amigos', FALSE, TRUE),
('Sirve un plato de queso', 'amigos', FALSE, TRUE),
('Sirve una cesta de pan', 'amigos', FALSE, TRUE),
('Sirve una taza de chocolate', 'amigos', FALSE, TRUE),
('Comparte un chiste corto', 'amigos', FALSE, TRUE),
('Comparte una anécdota de amistad', 'amigos', FALSE, TRUE),
('Comparte una canción divertida', 'amigos', FALSE, TRUE),
('Comparte una receta de aperitivo', 'amigos', FALSE, TRUE),
('Comparte una recomendación de película', 'amigos', FALSE, TRUE),
('Cuenta un chiste que haga reír', 'amigos', FALSE, TRUE),
('Cuenta una anécdota de la última salida', 'amigos', FALSE, TRUE),
('Cuenta un recuerdo divertido', 'amigos', FALSE, TRUE),
('Cuenta una historia de la infancia', 'amigos', FALSE, TRUE),
('Cuenta una ocurrencia del día', 'amigos', FALSE, TRUE),
('Propón un brindis', 'amigos', FALSE, TRUE),
('Propón una merienda compartida', 'amigos', FALSE, TRUE),
('Propón un juego de mesa', 'amigos', FALSE, TRUE),
('Propón una canción para cerrar', 'amigos', FALSE, TRUE),
('Propón una ronda de preguntas', 'amigos', FALSE, TRUE),
('Elige una bebida', 'amigos', FALSE, TRUE),
('Elige un aperitivo', 'amigos', FALSE, TRUE),
('Elige un postre', 'amigos', FALSE, TRUE),
('Elige una canción', 'amigos', FALSE, TRUE),
('Elige una actividad', 'amigos', FALSE, TRUE),
('Organiza una mesa de bebidas', 'amigos', FALSE, TRUE),
('Cuenta un chiste que haga reír a dos personas', 'amigos', FALSE, TRUE),
('Organiza una merienda', 'amigos', FALSE, TRUE),
('Organiza una partida', 'amigos', FALSE, TRUE),
('Organiza una ronda de brindis', 'amigos', FALSE, TRUE),
('Haz un brindis', 'amigos', FALSE, TRUE),
('Haz un gesto divertido', 'amigos', FALSE, TRUE),
('Haz un comentario simpático', 'amigos', FALSE, TRUE),
('Haz una imitación breve', 'amigos', FALSE, TRUE),
('Haz una foto divertida', 'amigos', FALSE, TRUE),
('Pide una opinión sobre la comida', 'amigos', FALSE, TRUE),
('Pide una canción para la lista', 'amigos', FALSE, TRUE),
('Pide un cuento corto', 'amigos', FALSE, TRUE),
('Pide una mano con la bandeja', 'amigos', FALSE, TRUE),
('Pide una recomendación de bebida', 'amigos', FALSE, TRUE),
('Recuérda el mejor chiste', 'amigos', FALSE, TRUE),
('Recuérda la hora de la merienda', 'amigos', FALSE, TRUE),
('Recuérda una canción compartida', 'amigos', FALSE, TRUE),
('Recuérda una bebida favorita', 'amigos', FALSE, TRUE),
('Recuérda una historia divertida', 'amigos', FALSE, TRUE),
('Brinda por la amistad', 'amigos', FALSE, TRUE),
('Brinda por la sobremesa', 'amigos', FALSE, TRUE),
('Brinda por las risas', 'amigos', FALSE, TRUE),
('Brinda por la próxima ronda', 'amigos', FALSE, TRUE),
('Brinda por la comida', 'amigos', FALSE, TRUE),
('Prueba un aperitivo', 'amigos', FALSE, TRUE),
('Prueba un postre', 'amigos', FALSE, TRUE),
('Prueba una bebida', 'amigos', FALSE, TRUE),
('Prueba un plato de la casa', 'amigos', FALSE, TRUE),
('Prueba una selección de dulces', 'amigos', FALSE, TRUE),
('Crea un nombre para el aperitivo', 'amigos', FALSE, TRUE),
('Crea un menú sencillo', 'amigos', FALSE, TRUE),
('Crea una lista de canciones', 'amigos', FALSE, TRUE),
('Inventa una canción de treinta segundos sobre la fiesta', 'amigos', FALSE, TRUE),
('Crea un ritual de brindis', 'amigos', FALSE, TRUE),
('Comparte un recuerdo de fiesta', 'amigos', FALSE, TRUE),
('Comparte un dato sobre la bebida', 'amigos', FALSE, TRUE),
('Comparte una recomendación de comida', 'amigos', FALSE, TRUE),
('Comparte un gesto de amistad', 'amigos', FALSE, TRUE),
('Comparte una broma ligera', 'amigos', FALSE, TRUE),
('Empieza una canción animada', 'amigos', FALSE, TRUE),
('Empieza un juego de preguntas', 'amigos', FALSE, TRUE),
('Haz que alguien elija una canción y baila con ella', 'amigos', FALSE, TRUE),
('Empieza un aperitivo', 'amigos', FALSE, TRUE),
('Empieza una conversación sobre comida', 'amigos', FALSE, TRUE),
('Termina la canción con una nota divertida', 'amigos', FALSE, TRUE),
('Termina la ronda con un aplauso', 'amigos', FALSE, TRUE),
('Termina la merienda con un cumplido', 'amigos', FALSE, TRUE),
('Termina el juego con una risa', 'amigos', FALSE, TRUE),
('Termina la charla con una promesa', 'amigos', FALSE, TRUE),
('Escoge el aperitivo más sencillo', 'amigos', FALSE, TRUE),
('Escoge la canción más alegre', 'amigos', FALSE, TRUE),
('Escoge un postre para compartir', 'amigos', FALSE, TRUE),
('Escoge un juego para todos', 'amigos', FALSE, TRUE),
('Escoge una bebida sin alcohol', 'amigos', FALSE, TRUE),
('Ofrece un vaso de agua', 'amigos', FALSE, TRUE),
('Ofrece un trozo de pan', 'amigos', FALSE, TRUE),
('Ofrece una risa', 'amigos', FALSE, TRUE),
('Ofrece una plaza en el sofá', 'amigos', FALSE, TRUE),
('Ofrece una canción', 'amigos', FALSE, TRUE),
('Sube el volumen de la música', 'amigos', FALSE, TRUE),
('Sirve una bebida a otra persona y pregunta qué prefiere', 'amigos', FALSE, TRUE),
('Sube la temperatura de la conversación', 'amigos', FALSE, TRUE),
('Sube el ritmo del baile', 'amigos', FALSE, TRUE),
('Cuenta un chiste ligero sobre una situación de la reunión', 'amigos', FALSE, TRUE),
('Baja el volumen de la música', 'amigos', FALSE, TRUE),
('Baja la intensidad de la discusión sobre la comida', 'amigos', FALSE, TRUE),
('Baja la velocidad de la ronda', 'amigos', FALSE, TRUE),
('Baja el tono de la broma', 'amigos', FALSE, TRUE),
('Baja la prisa de la merienda', 'amigos', FALSE, TRUE),
('Lanza una pregunta de comida', 'amigos', FALSE, TRUE),
('Lanza un reto de canción', 'amigos', FALSE, TRUE),
('Lanza una anécdota improvisada', 'amigos', FALSE, TRUE),
('Lanza un juego de gestos con comida', 'amigos', FALSE, TRUE),
('Lanza una votación de bebidas', 'amigos', FALSE, TRUE),
('Repite el estribillo', 'amigos', FALSE, TRUE),
('Repite una frase de una canción', 'amigos', FALSE, TRUE),
('Haz una imitación breve de alguien que elija el grupo', 'amigos', FALSE, TRUE),
('Haz un aplauso breve y anima a que alguien cante', 'amigos', FALSE, TRUE),
('Repite una nota musical', 'amigos', FALSE, TRUE),
('Pon una canción de fondo', 'amigos', FALSE, TRUE),
('Pon la mesa de los aperitivos', 'amigos', FALSE, TRUE),
('Pon un vaso de hielo', 'amigos', FALSE, TRUE),
('Pon un plato de dulces', 'amigos', FALSE, TRUE),
('Pon una pregunta de comida', 'amigos', FALSE, TRUE),
('Presta atención a una receta', 'amigos', FALSE, TRUE),
('Presta el móvil a otra persona', 'amigos', FALSE, TRUE),
('Presta el vaso a alguien', 'amigos', FALSE, TRUE),
('Presta la cámara a un amigo', 'amigos', FALSE, TRUE),
('Presta el agitador a alguien', 'amigos', FALSE, TRUE),
('Abre una botella de bebida', 'amigos', FALSE, TRUE),
('Abre un paquete de galletas', 'amigos', FALSE, TRUE),
('Abre una partida de naipes con un aperitivo', 'amigos', FALSE, TRUE),
('Abre una carta de conversación sobre comida', 'amigos', FALSE, TRUE),
('Abre un turno de bromas', 'amigos', FALSE, TRUE),
('Cierra la botella de bebida', 'amigos', FALSE, TRUE),
('Cierra el paquete de galletas', 'amigos', FALSE, TRUE),
('Cierra la carta de conversación sobre comida', 'amigos', FALSE, TRUE),
('Cierra el turno de bromas', 'amigos', FALSE, TRUE),
('Cierra la ronda de preguntas', 'amigos', FALSE, TRUE),
('Acelera el ritmo de una canción', 'amigos', FALSE, TRUE),
('Acelera la música', 'amigos', FALSE, TRUE),
('Acelera la conversación', 'amigos', FALSE, TRUE),
('Acelera el juego', 'amigos', FALSE, TRUE),
('Acelera el servicio de la merienda', 'amigos', FALSE, TRUE),
('Frena el ritmo de una canción', 'amigos', FALSE, TRUE),
('Frena el baile improvisado', 'amigos', FALSE, TRUE),
('Frena la ronda de bromas', 'amigos', FALSE, TRUE),
('Frena el juego de preguntas', 'amigos', FALSE, TRUE),
('Frena la conversación de la merienda', 'amigos', FALSE, TRUE),
('Invita a probar un aperitivo', 'amigos', FALSE, TRUE),
('Invita a elegir una canción', 'amigos', FALSE, TRUE),
('Invita a jugar una ronda de bromas', 'amigos', FALSE, TRUE),
('Invita a contar una anécdota de comida', 'amigos', FALSE, TRUE),
('Invita a provocar una risa', 'amigos', FALSE, TRUE),
('Dedica una melodía a alguien', 'amigos', FALSE, TRUE),
('Dedica un cumplido divertido', 'amigos', FALSE, TRUE),
('Dedica una sonrisa al grupo', 'amigos', FALSE, TRUE),
('Dedica un brindis a la amistad', 'amigos', FALSE, TRUE),
('Dedica un baile breve', 'amigos', FALSE, TRUE),
('Mantén contacto visual con alguien unos segundos', 'picantes', FALSE, TRUE),
('Haz contacto visual breve y sonríe si recibes permiso', 'picantes', FALSE, TRUE),
('Mantén el contacto visual durante una canción', 'picantes', FALSE, TRUE),
('Mantén la mirada cómplice con alguien', 'picantes', FALSE, TRUE),
('Susurra un cumplido sin mencionar la palabra clave', 'picantes', FALSE, TRUE),
('Toca el hombro de alguien', 'picantes', FALSE, TRUE),
('Toca el codo de alguien con permiso', 'picantes', FALSE, TRUE),
('Toca la mano de alguien con permiso', 'picantes', FALSE, TRUE),
('Toca la esquina de la mesa junto a alguien', 'picantes', FALSE, TRUE),
('Toca el hombro de alguien al saludar', 'picantes', FALSE, TRUE),
('Acerca tu silla a alguien con permiso', 'picantes', FALSE, TRUE),
('Acerca el oído a alguien para hablar bajo', 'picantes', FALSE, TRUE),
('Acerca un mensaje a alguien con una sonrisa', 'picantes', FALSE, TRUE),
('Acerca tu hombro al de alguien', 'picantes', FALSE, TRUE),
('Acerca una copa a la de alguien', 'picantes', FALSE, TRUE),
('Inclínate hacia alguien para compartir una idea', 'picantes', FALSE, TRUE),
('Inclínate un poco hacia alguien', 'picantes', FALSE, TRUE),
('Inclínate hacia la persona que esté a tu lado', 'picantes', FALSE, TRUE),
('Inclínate hacia alguien con curiosidad', 'picantes', FALSE, TRUE),
('Inclínate hacia el centro de la mesa', 'picantes', FALSE, TRUE),
('Susurra un cumplido a alguien', 'picantes', FALSE, TRUE),
('Susurra una pregunta divertida a alguien', 'picantes', FALSE, TRUE),
('Susurra un plan divertido a alguien', 'picantes', FALSE, TRUE),
('Susurra un detalle simpático a alguien', 'picantes', FALSE, TRUE),
('Susurra una broma inocente a alguien', 'picantes', FALSE, TRUE),
('Dedica una sonrisa a alguien', 'picantes', FALSE, TRUE),
('Dedica una mirada a alguien', 'picantes', FALSE, TRUE),
('Dedica un cumplido a alguien', 'picantes', FALSE, TRUE),
('Dedica un gesto de complicidad a alguien', 'picantes', FALSE, TRUE),
('Dedica una canción a alguien', 'picantes', FALSE, TRUE),
('Haz un cumplido sincero', 'picantes', FALSE, TRUE),
('Haz un gesto de complicidad', 'picantes', FALSE, TRUE),
('Haz una mirada efímera', 'picantes', FALSE, TRUE),
('Haz una broma inocente', 'picantes', FALSE, TRUE),
('Haz un aplauso para alguien', 'picantes', FALSE, TRUE),
('Elige un cumplido para alguien', 'picantes', FALSE, TRUE),
('Elige una mirada para alguien', 'picantes', FALSE, TRUE),
('Elige una sonrisa para alguien', 'picantes', FALSE, TRUE),
('Elige un gesto de complicidad', 'picantes', FALSE, TRUE),
('Elige un consejo de confianza', 'picantes', FALSE, TRUE),
('Invita a alguien a bailar una canción', 'picantes', FALSE, TRUE),
('Invita a alguien a probar un juego', 'picantes', FALSE, TRUE),
('Invita a alguien a sentarse cerca', 'picantes', FALSE, TRUE),
('Invita a alguien a cambiar de tema', 'picantes', FALSE, TRUE),
('Invita a alguien a provocar una risa', 'picantes', FALSE, TRUE),
('Rodea a alguien con un abrazo breve', 'picantes', FALSE, TRUE),
('Rodea a alguien con el brazo en los hombros con permiso', 'picantes', FALSE, TRUE),
('Rodea a alguien con una foto', 'picantes', FALSE, TRUE),
('Rodea a alguien con una sonrisa', 'picantes', FALSE, TRUE),
('Rodea el hombro de alguien con la mano', 'picantes', FALSE, TRUE),
('Apoya la mano en el hombro de alguien con permiso', 'picantes', FALSE, TRUE),
('Apoya el codo junto al de alguien', 'picantes', FALSE, TRUE),
('Apoya la rodilla cerca de la de alguien', 'picantes', FALSE, TRUE),
('Apoya el pie junto al de alguien', 'picantes', FALSE, TRUE),
('Apoya la mano en la mesa cerca de alguien', 'picantes', FALSE, TRUE),
('Cruza los dedos con los de alguien con permiso', 'picantes', FALSE, TRUE),
('Cruza una mirada con alguien', 'picantes', FALSE, TRUE),
('Cruza un brindis con alguien', 'picantes', FALSE, TRUE),
('Cruza una sonrisa con alguien', 'picantes', FALSE, TRUE),
('Cruza una conversación con alguien', 'picantes', FALSE, TRUE),
('Entrelaza los dedos con los de alguien con permiso', 'picantes', FALSE, TRUE),
('Entrelaza los brazos con alguien en una foto', 'picantes', FALSE, TRUE),
('Entrelaza un gesto de confianza con alguien', 'picantes', FALSE, TRUE),
('Entrelaza una mirada cómplice con alguien', 'picantes', FALSE, TRUE),
('Entrelaza una copa con la de alguien', 'picantes', FALSE, TRUE),
('Abraza a alguien por unos segundos', 'picantes', FALSE, TRUE),
('Abraza a alguien al llegar', 'picantes', FALSE, TRUE),
('Abraza a alguien antes de una canción', 'picantes', FALSE, TRUE),
('Abraza a alguien al saludar', 'picantes', FALSE, TRUE),
('Abraza a alguien al terminar la ronda', 'picantes', FALSE, TRUE),
('Mueve tu silla un poco más cerca de alguien con permiso', 'picantes', FALSE, TRUE),
('Mueve la cabeza hacia alguien para escuchar', 'picantes', FALSE, TRUE),
('Mueve la mano hacia alguien con permiso', 'picantes', FALSE, TRUE),
('Mueve la mirada hacia alguien', 'picantes', FALSE, TRUE),
('Mueve el cuerpo hacia el centro del grupo', 'picantes', FALSE, TRUE),
('Mira a alguien con atención cordial', 'picantes', FALSE, TRUE),
('Mira a alguien con aprobación', 'picantes', FALSE, TRUE),
('Mira a alguien con curiosidad', 'picantes', FALSE, TRUE),
('Mira a alguien con una sonrisa', 'picantes', FALSE, TRUE),
('Mira a alguien durante una canción', 'picantes', FALSE, TRUE),
('Dibuja un corazón en una servilleta', 'picantes', FALSE, TRUE),
('Dibuja un garabato simpático en una nota', 'picantes', FALSE, TRUE),
('Dibuja un gesto de corazón con los dedos', 'picantes', FALSE, TRUE),
('Dibuja un mapa de la mesa', 'picantes', FALSE, TRUE),
('Dibuja un retrato improvisado', 'picantes', FALSE, TRUE),
('Regala un cumplido sincero', 'picantes', FALSE, TRUE),
('Regala un apretón de manos', 'picantes', FALSE, TRUE),
('Regala una sonrisa especial', 'picantes', FALSE, TRUE),
('Regala una canción dedicada', 'picantes', FALSE, TRUE),
('Regala un aperitivo compartido', 'picantes', FALSE, TRUE),
('Comparte una mirada de complicidad', 'picantes', FALSE, TRUE),
('Comparte un momento de complicidad', 'picantes', FALSE, TRUE),
('Comparte un cumplido sin motivo', 'picantes', FALSE, TRUE),
('Comparte una risa cercana', 'picantes', FALSE, TRUE),
('Comparte un gesto de afinidad', 'picantes', FALSE, TRUE),
('Ponte al lado de alguien durante una canción', 'picantes', FALSE, TRUE),
('Ponte a la altura de otra persona', 'picantes', FALSE, TRUE),
('Dedica un cumplido coqueto con permiso', 'picantes', FALSE, TRUE),
('Presenta una prenda de fiesta que hayas elegido', 'picantes', FALSE, TRUE),
('Ponte junto a alguien al saludar', 'picantes', FALSE, TRUE),
('Atrapa la mirada de alguien con una sonrisa', 'picantes', FALSE, TRUE),
('Atrapa un gesto de alguien con complicidad', 'picantes', FALSE, TRUE),
('Atrapa la atención de alguien con humor', 'picantes', FALSE, TRUE),
('Atrapa una reacción con una broma', 'picantes', FALSE, TRUE),
('Atrapa un aplauso al compás de una canción', 'picantes', FALSE, TRUE),
('Tienta a alguien con un aperitivo', 'picantes', FALSE, TRUE),
('Tienta a alguien a bailar', 'picantes', FALSE, TRUE),
('Tienta a alguien a jugar', 'picantes', FALSE, TRUE),
('Tienta a alguien a probar un postre', 'picantes', FALSE, TRUE),
('Tienta a alguien a hablar al oído', 'picantes', FALSE, TRUE),
('Propón a alguien un baile', 'picantes', FALSE, TRUE),
('Propón a alguien un juego de pareja', 'picantes', FALSE, TRUE),
('Propón a alguien una conversación privada', 'picantes', FALSE, TRUE),
('Propón a alguien un brindis', 'picantes', FALSE, TRUE),
('Propón a alguien un cumplido', 'picantes', FALSE, TRUE),
('Sostén una mirada cálida con alguien', 'picantes', FALSE, TRUE),
('Sostén la mano de alguien un momento', 'picantes', FALSE, TRUE),
('Sostén una sonrisa compartida', 'picantes', FALSE, TRUE),
('Sostén la conversación con alguien', 'picantes', FALSE, TRUE),
('Sostén un momento de complicidad', 'picantes', FALSE, TRUE),
('Escucha una canción susurrada', 'picantes', FALSE, TRUE),
('Escucha una propuesta con paciencia', 'picantes', FALSE, TRUE),
('Escucha un consejo con paciencia', 'picantes', FALSE, TRUE),
('Escucha un consejo sincero de alguien', 'picantes', FALSE, TRUE),
('Escucha una historia compartida', 'picantes', FALSE, TRUE),
('Juega a un juego de miradas', 'picantes', FALSE, TRUE),
('Juega a un juego de gestos', 'picantes', FALSE, TRUE),
('Juega a un juego de propuestas', 'picantes', FALSE, TRUE),
('Juega a un juego de cumplidos', 'picantes', FALSE, TRUE),
('Juega a un juego de pareja', 'picantes', FALSE, TRUE),
('Pon una canción pausada', 'picantes', FALSE, TRUE),
('Pon un disco de fondo', 'picantes', FALSE, TRUE),
('Pon una mirada de advertencia juguetona', 'picantes', FALSE, TRUE),
('Pon un mensaje de complicidad', 'picantes', FALSE, TRUE),
('Pon un ambiente tranquilo', 'picantes', FALSE, TRUE),
('Busca la mirada de alguien con una sonrisa', 'picantes', FALSE, TRUE),
('Busca un momento para conversar', 'picantes', FALSE, TRUE),
('Busca una reacción divertida', 'picantes', FALSE, TRUE),
('Busca una aproximación con permiso', 'picantes', FALSE, TRUE),
('Busca una mirada especial', 'picantes', FALSE, TRUE),
('Atrapa la mano de alguien con delicadeza', 'picantes', FALSE, TRUE),
('Atrapa una sonrisa en el momento justo', 'picantes', FALSE, TRUE),
('Atrapa un gesto de cariño', 'picantes', FALSE, TRUE),
('Atrapa la atención durante una canción', 'picantes', FALSE, TRUE),
('Atrapa un aplauso cercano', 'picantes', FALSE, TRUE),
('Comparte una broma interna', 'picantes', FALSE, TRUE),
('Comparte un cumplido personal', 'picantes', FALSE, TRUE),
('Comparte una mirada cálida', 'picantes', FALSE, TRUE),
('Comparte un instante de complicidad', 'picantes', FALSE, TRUE),
('Comparte una atención cariñosa', 'picantes', FALSE, TRUE),
('Cuenta un rumor inventado sobre una fiesta', 'salseo', FALSE, TRUE),
('Cuenta un chisme ficticio sobre un viaje', 'salseo', FALSE, TRUE),
('Cuenta una anécdota falsa sobre un conocido', 'salseo', FALSE, TRUE),
('Cuenta un rumor absurdo sobre una cita', 'salseo', FALSE, TRUE),
('Cuenta un malentendido real de la fiesta sin dar nombres', 'salseo', FALSE, TRUE),
('Inventa un rumor absurdo', 'salseo', FALSE, TRUE),
('Inventa una discusión por un sofá', 'salseo', FALSE, TRUE),
('Inventa un romance de caricatura', 'salseo', FALSE, TRUE),
('Inventa un plan de fuga', 'salseo', FALSE, TRUE),
('Inventa una traición de pega', 'salseo', FALSE, TRUE),
('Difunde un rumor falso y divertido', 'salseo', FALSE, TRUE),
('Difunde una versión exagerada de una anécdota', 'salseo', FALSE, TRUE),
('Difunde un chisme inventado', 'salseo', FALSE, TRUE),
('Difunde una noticia de pega', 'salseo', FALSE, TRUE),
('Difunde una anécdota sin fundamento', 'salseo', FALSE, TRUE),
('Pregunta a alguien qué rumor conoce sin señalar a nadie', 'salseo', FALSE, TRUE),
('Defiende una teoría conspirativa absurda', 'salseo', FALSE, TRUE),
('Cuenta dos versiones opuestas de un mismo recuerdo', 'salseo', FALSE, TRUE),
('Defiende una opinión impopular', 'salseo', FALSE, TRUE),
('Defiende una excusa inesperada', 'salseo', FALSE, TRUE),
('Ataca una idea absurda', 'salseo', FALSE, TRUE),
('Ataca una costumbre molesta', 'salseo', FALSE, TRUE),
('Ataca una decisión absurda', 'salseo', FALSE, TRUE),
('Ataca un rumor con argumentos', 'salseo', FALSE, TRUE),
('Ataca un plan de la casa con argumentos', 'salseo', FALSE, TRUE),
('Plantea un rumor inventado', 'salseo', FALSE, TRUE),
('Plantea una calumnia de pega', 'salseo', FALSE, TRUE),
('Haz una pregunta incómoda sobre una ex pareja', 'salseo', FALSE, TRUE),
('Plantea un chiste con mala leche', 'salseo', FALSE, TRUE),
('Plantea una historia sin final', 'salseo', FALSE, TRUE),
('Escucha un sermón absurdo', 'salseo', FALSE, TRUE),
('Escucha un diálogo de novela clásica', 'salseo', FALSE, TRUE),
('Escucha una queja dramatizada', 'salseo', FALSE, TRUE),
('Escucha un análisis inventado', 'salseo', FALSE, TRUE),
('Escucha una conversación de grupo', 'salseo', FALSE, TRUE),
('Pregunta por qué alguien llegó tarde', 'salseo', FALSE, TRUE),
('Pregunta por qué alguien eligió ese aperitivo', 'salseo', FALSE, TRUE),
('Pregunta por qué alguien cambia de opinión', 'salseo', FALSE, TRUE),
('Pregunta por qué alguien tiene una historia rara', 'salseo', FALSE, TRUE),
('Pregunta por qué alguien está tan complaciente', 'salseo', FALSE, TRUE),
('Exagera un detalle sin importancia', 'salseo', FALSE, TRUE),
('Exagera un rumor benigno', 'salseo', FALSE, TRUE),
('Exagera una anécdota corriente', 'salseo', FALSE, TRUE),
('Exagera un gesto poco convincente', 'salseo', FALSE, TRUE),
('Exagera una preferencia personal', 'salseo', FALSE, TRUE),
('Replica a un rumor con una invención', 'salseo', FALSE, TRUE),
('Replica a una pregunta absurda', 'salseo', FALSE, TRUE),
('Replica a una acusación de pega', 'salseo', FALSE, TRUE),
('Replica a una crítica teatral', 'salseo', FALSE, TRUE),
('Replica a una opinión impopular', 'salseo', FALSE, TRUE),
('Acelera un rumor con detalles', 'salseo', FALSE, TRUE),
('Acelera un chisme con detalles', 'salseo', FALSE, TRUE),
('Acelera un argumento con detalles', 'salseo', FALSE, TRUE),
('Acelera una historia con detalles', 'salseo', FALSE, TRUE),
('Acelera una discusión con detalles', 'salseo', FALSE, TRUE),
('Escandaliza al grupo con un rumor absurdo', 'salseo', FALSE, TRUE),
('Escandaliza a alguien con una historia falsa', 'salseo', FALSE, TRUE),
('Escandaliza a la mesa con una afirmación rara', 'salseo', FALSE, TRUE),
('Escandaliza al grupo con una broma teatral', 'salseo', FALSE, TRUE),
('Escandaliza a alguien con una noticia inventada', 'salseo', FALSE, TRUE),
('Cuchichea un rumor sin nombres', 'salseo', FALSE, TRUE),
('Cuchichea una duda absurda', 'salseo', FALSE, TRUE),
('Cuchichea una historia de fondo', 'salseo', FALSE, TRUE),
('Cuchichea un comentario malintencionado', 'salseo', FALSE, TRUE),
('Cuchichea una acotación maliciosa', 'salseo', FALSE, TRUE),
('Relata un episodio inventado', 'salseo', FALSE, TRUE),
('Relata una pelea fingida', 'salseo', FALSE, TRUE),
('Relata un encuentro casual', 'salseo', FALSE, TRUE),
('Relata un error de memoria', 'salseo', FALSE, TRUE),
('Relata un chisme de pega', 'salseo', FALSE, TRUE),
('Jura que viste algo raro', 'salseo', FALSE, TRUE),
('Jura que escuchaste una historia extraña', 'salseo', FALSE, TRUE),
('Jura que tu versión era la correcta', 'salseo', FALSE, TRUE),
('Jura que el rumor ya se resolvió', 'salseo', FALSE, TRUE),
('Jura que el plan era espontáneo', 'salseo', FALSE, TRUE),
('Niega haber leído el mensaje', 'salseo', FALSE, TRUE),
('Niega haber dado la bienvenida', 'salseo', FALSE, TRUE),
('Niega haber visto el documento', 'salseo', FALSE, TRUE),
('Niega haber recibido la llamada', 'salseo', FALSE, TRUE),
('Niega haber leído la conversación', 'salseo', FALSE, TRUE),
('Admite que se te ha escapado un chiste', 'salseo', FALSE, TRUE),
('Admite que tu versión cambió', 'salseo', FALSE, TRUE),
('Admite que confundiste dos nombres', 'salseo', FALSE, TRUE),
('Admite que escuchaste otra historia', 'salseo', FALSE, TRUE),
('Admite que la discusión te divirtió', 'salseo', FALSE, TRUE),
('Declara que el plan cambió de golpe', 'salseo', FALSE, TRUE),
('Declara que el rumor se exageró', 'salseo', FALSE, TRUE),
('Declara que la comida estaba deliciosa', 'salseo', FALSE, TRUE),
('Declara que la película fue un desastre', 'salseo', FALSE, TRUE),
('Declara que nadie entendió nada', 'salseo', FALSE, TRUE),
('Cambia de bando durante una discusión inventada', 'salseo', FALSE, TRUE),
('Cambia de opinión sobre un rumor falso', 'salseo', FALSE, TRUE),
('Cambia de tema cuando empiece el chisme', 'salseo', FALSE, TRUE),
('Cambia de gesto durante una discusión', 'salseo', FALSE, TRUE),
('Cambia de tema de forma teatral', 'salseo', FALSE, TRUE),
('Apoya el bando equivocado en un debate inventado', 'salseo', FALSE, TRUE),
('Apoya a una persona en un chisme de pega', 'salseo', FALSE, TRUE),
('Apoya una versión exagerada del té', 'salseo', FALSE, TRUE),
('Acepta un secreto y promete guardarlo', 'salseo', FALSE, TRUE),
('Apoya un argumento absurdo', 'salseo', FALSE, TRUE),
('Fabrica una coartada para una ausencia', 'salseo', FALSE, TRUE),
('Fabrica una señal falsa para un juego', 'salseo', FALSE, TRUE),
('Fabrica un testimonio inventado', 'salseo', FALSE, TRUE),
('Fabrica un rumor con fecha falsa', 'salseo', FALSE, TRUE),
('Fabrica una explicación absurda', 'salseo', FALSE, TRUE),
('Propaga un rumor falso', 'salseo', FALSE, TRUE),
('Propaga un chiste ligero', 'salseo', FALSE, TRUE),
('Cuenta un secreto que sea claramente inventado', 'salseo', FALSE, TRUE),
('Propaga un rumor con más detalles', 'salseo', FALSE, TRUE),
('Propaga una duda propagada', 'salseo', FALSE, TRUE),
('Contradice la versión local', 'salseo', FALSE, TRUE),
('Contradice una buena intención', 'salseo', FALSE, TRUE),
('Contradice un relato inventado', 'salseo', FALSE, TRUE),
('Contradice una teoría simple', 'salseo', FALSE, TRUE),
('Contradice un plan de última hora', 'salseo', FALSE, TRUE),
('Distingue un hecho de un rumor', 'salseo', FALSE, TRUE),
('Distingue un chiste de una acusación', 'salseo', FALSE, TRUE),
('Distingue una opinión de un dato', 'salseo', FALSE, TRUE),
('Distingue una broma de un rumor', 'salseo', FALSE, TRUE),
('Distingue una versión de un testimonio', 'salseo', FALSE, TRUE),
('Marca el ritmo de la discusión', 'salseo', FALSE, TRUE),
('Marca un giro de trama', 'salseo', FALSE, TRUE),
('Marca un giro de tema', 'salseo', FALSE, TRUE),
('Marca un giro argumental', 'salseo', FALSE, TRUE),
('Marca un giro de chisme', 'salseo', FALSE, TRUE),
('Convierte un chiste en un rumor', 'salseo', FALSE, TRUE),
('Convierte una anécdota en un drama', 'salseo', FALSE, TRUE),
('Convierte un detalle en una acusación', 'salseo', FALSE, TRUE),
('Convierte un error en una noticia', 'salseo', FALSE, TRUE),
('Convierte una pregunta en un escándalo', 'salseo', FALSE, TRUE),
('Responde a una pregunta con una invención', 'salseo', FALSE, TRUE),
('Responde a un argumento con otro argumento inventado', 'salseo', FALSE, TRUE),
('Responde a un rumor con un rumor inverso', 'salseo', FALSE, TRUE),
('Responde a un chiste con una seriedad fingida', 'salseo', FALSE, TRUE),
('Responde a una acusación con una coartada', 'salseo', FALSE, TRUE),
('Cierra la discusión con un acuerdo absurdo', 'salseo', FALSE, TRUE),
('Cierra el rumor con una rectificación cómica', 'salseo', FALSE, TRUE),
('Cierra la historia con un giro inesperado', 'salseo', FALSE, TRUE),
('Cierra la pelea con una disculpa teatral', 'salseo', FALSE, TRUE),
('Cierra la ronda con una conclusión ridícula', 'salseo', FALSE, TRUE),
('Formula la pregunta más indiscreta de la noche', 'salseo', FALSE, TRUE),
('Formula el rumor más absurdo de la ronda', 'salseo', FALSE, TRUE),
('Formula el debate más inútil de la mesa', 'salseo', FALSE, TRUE),
('Formula la acusación más teatral del grupo', 'salseo', FALSE, TRUE),
('Formula la historia más exagerada del día', 'salseo', FALSE, TRUE),
('Obtiene una confesión ficticia', 'salseo', FALSE, TRUE),
('Obtiene una reacción misteriosa', 'salseo', FALSE, TRUE),
('Obtiene un testimonio absurdo', 'salseo', FALSE, TRUE),
('Obtiene una respuesta ridícula', 'salseo', FALSE, TRUE),
('Obtiene una reacción teatral', 'salseo', FALSE, TRUE),
('Canta una canción a pleno pulmón', 'extremos', FALSE, TRUE),
('Canta el estribillo de una canción', 'extremos', FALSE, TRUE),
('Canta una escala con mucha voz', 'extremos', FALSE, TRUE),
('Cuenta una anécdota íntima que tú quieras compartir', 'extremos', FALSE, TRUE),
('Canta un fragmento de una ópera', 'extremos', FALSE, TRUE),
('Levanta el volumen de la música', 'extremos', FALSE, TRUE),
('Levanta una tarjeta en el aire', 'extremos', FALSE, TRUE),
('Haz un brindis junto a la piscina sin entrar al agua', 'extremos', FALSE, TRUE),
('Levanta un aplauso estrepitoso', 'extremos', FALSE, TRUE),
('Levanta un cartel improvisado', 'extremos', FALSE, TRUE),
('Salta diez veces en el sitio', 'extremos', FALSE, TRUE),
('Salta al ritmo de la música', 'extremos', FALSE, TRUE),
('Salta con un salto corto', 'extremos', FALSE, TRUE),
('Salta hasta el final de la canción', 'extremos', FALSE, TRUE),
('Salta sobre una línea imaginaria', 'extremos', FALSE, TRUE),
('Corre durante diez segundos', 'extremos', FALSE, TRUE),
('Corre al ritmo del beat', 'extremos', FALSE, TRUE),
('Corre hasta una pared y vuelve', 'extremos', FALSE, TRUE),
('Corre en círculos pequeños', 'extremos', FALSE, TRUE),
('Corre mientras alguien aplaude', 'extremos', FALSE, TRUE),
('Grita un viva', 'extremos', FALSE, TRUE),
('Grita un nombre inventado', 'extremos', FALSE, TRUE),
('Grita el final de una canción', 'extremos', FALSE, TRUE),
('Grita una frase de ánimo', 'extremos', FALSE, TRUE),
('Grita el título de una película', 'extremos', FALSE, TRUE),
('Recita un poema corto', 'extremos', FALSE, TRUE),
('Recita una receta imaginaria', 'extremos', FALSE, TRUE),
('Recita una lista inventada', 'extremos', FALSE, TRUE),
('Recita el guion de una obra', 'extremos', FALSE, TRUE),
('Recita un sermón teatral', 'extremos', FALSE, TRUE),
('Imita a un presentador exagerado', 'extremos', FALSE, TRUE),
('Imita a un personaje conocido', 'extremos', FALSE, TRUE),
('Imita a un bailarín exagerado', 'extremos', FALSE, TRUE),
('Imita a un profesor dramático', 'extremos', FALSE, TRUE),
('Imita a un narrador teatral', 'extremos', FALSE, TRUE),
('Haz una ronda de flexiones', 'extremos', FALSE, TRUE),
('Haz un discurso exagerado', 'extremos', FALSE, TRUE),
('Haz un ejercicio de equilibrio', 'extremos', FALSE, TRUE),
('Haz una reacción estruendosa', 'extremos', FALSE, TRUE),
('Haz un movimiento de cámara improvisado', 'extremos', FALSE, TRUE),
('Baila al ritmo de una canción', 'extremos', FALSE, TRUE),
('Baila durante toda la canción', 'extremos', FALSE, TRUE),
('Baila con el grupo', 'extremos', FALSE, TRUE),
('Baila como si estuviera en un estadio', 'extremos', FALSE, TRUE),
('Baila con una sonrisa enorme', 'extremos', FALSE, TRUE),
('Agita un vaso de plástico', 'extremos', FALSE, TRUE),
('Agita una servilleta', 'extremos', FALSE, TRUE),
('Agita un pañuelo', 'extremos', FALSE, TRUE),
('Agita un ramo de flores', 'extremos', FALSE, TRUE),
('Agita una botella vacía', 'extremos', FALSE, TRUE),
('Toca un tambor improvisado', 'extremos', FALSE, TRUE),
('Toca el ritmo de la mesa', 'extremos', FALSE, TRUE),
('Toca una palmada en el hombro', 'extremos', FALSE, TRUE),
('Toca una guitarra', 'extremos', FALSE, TRUE),
('Toca un instrumento de cuerda', 'extremos', FALSE, TRUE),
('Actúa como locutor y anuncia al ganador de la ronda', 'extremos', FALSE, TRUE),
('Sube el volumen de una frase durante diez segundos', 'extremos', FALSE, TRUE),
('Haz una pose de final de programa', 'extremos', FALSE, TRUE),
('Haz un sonido original y marca el ritmo con los dedos', 'extremos', FALSE, TRUE),
('Canta una estrofa con la persona que elijas', 'extremos', FALSE, TRUE),
('Sostén un aplauso de treinta segundos', 'extremos', FALSE, TRUE),
('Sostén una nota musical', 'extremos', FALSE, TRUE),
('Sostén un equilibrio precario', 'extremos', FALSE, TRUE),
('Sostén una mirada intensa', 'extremos', FALSE, TRUE),
('Sostén una pose teatral', 'extremos', FALSE, TRUE),
('Tira un papel hacia la basura', 'extremos', FALSE, TRUE),
('Tira un poco de confeti', 'extremos', FALSE, TRUE),
('Tira un acertijo a los demás', 'extremos', FALSE, TRUE),
('Tira una pregunta al grupo', 'extremos', FALSE, TRUE),
('Tira un mensaje de ánimo', 'extremos', FALSE, TRUE),
('Atrapa un globo', 'extremos', FALSE, TRUE),
('Atrapa una nota de papel', 'extremos', FALSE, TRUE),
('Atrapa un peluche', 'extremos', FALSE, TRUE),
('Atrapa un objeto pequeño', 'extremos', FALSE, TRUE),
('Atrapa una reacción de sorpresa', 'extremos', FALSE, TRUE),
('Señala el foco de luz', 'extremos', FALSE, TRUE),
('Señala una silueta en la pared', 'extremos', FALSE, TRUE),
('Señala el ritmo de la música', 'extremos', FALSE, TRUE),
('Señala el techo de la sala', 'extremos', FALSE, TRUE),
('Señala un gesto hacia el público', 'extremos', FALSE, TRUE),
('Aguanta un equilibrio precario', 'extremos', FALSE, TRUE),
('Aguanta una risa contenida', 'extremos', FALSE, TRUE),
('Aguanta un personaje de teatro', 'extremos', FALSE, TRUE),
('Aguanta un texto de una canción', 'extremos', FALSE, TRUE),
('Aguanta una pose imposible', 'extremos', FALSE, TRUE),
('Clama un título de película', 'extremos', FALSE, TRUE),
('Clama un nombre de objeto', 'extremos', FALSE, TRUE),
('Clama un verso inventado', 'extremos', FALSE, TRUE),
('Clama el nombre de la canción', 'extremos', FALSE, TRUE),
('Clama un titular inventado', 'extremos', FALSE, TRUE),
('Gira alrededor de una persona con permiso', 'extremos', FALSE, TRUE),
('Gira sobre ti mismo', 'extremos', FALSE, TRUE),
('Gira en círculos', 'extremos', FALSE, TRUE),
('Gira al ritmo del beat', 'extremos', FALSE, TRUE),
('Gira con los ojos cerrados', 'extremos', FALSE, TRUE),
('Agáchate durante una canción', 'extremos', FALSE, TRUE),
('Agáchate sin tocar el suelo', 'extremos', FALSE, TRUE),
('Agáchate al ritmo del beat', 'extremos', FALSE, TRUE),
('Agáchate bajo una señal visible', 'extremos', FALSE, TRUE),
('Agáchate al terminar el estribillo', 'extremos', FALSE, TRUE),
('Brilla con una linterna', 'extremos', FALSE, TRUE),
('Brilla con una sonrisa enorme', 'extremos', FALSE, TRUE),
('Brilla al ritmo de la música', 'extremos', FALSE, TRUE),
('Brilla con una pose', 'extremos', FALSE, TRUE),
('Brilla al terminar la canción', 'extremos', FALSE, TRUE),
('Entra al centro de la sala con una presentación', 'extremos', FALSE, TRUE),
('Entra en modo actor con una entrada teatral', 'extremos', FALSE, TRUE),
('Entra en la ronda con un saludo', 'extremos', FALSE, TRUE),
('Entra al escenario improvisado', 'extremos', FALSE, TRUE),
('Entra con un gesto exagerado', 'extremos', FALSE, TRUE),
('Cierra la ronda con un gesto', 'extremos', FALSE, TRUE),
('Cierra la canción con un aplauso', 'extremos', FALSE, TRUE),
('Cierra el juego con una risa', 'extremos', FALSE, TRUE),
('Cierra la escena con una pose', 'extremos', FALSE, TRUE),
('Cierra el minuto con un movimiento', 'extremos', FALSE, TRUE),
('Bate el ritmo con el pie', 'extremos', FALSE, TRUE),
('Bate el pulso de la canción', 'extremos', FALSE, TRUE),
('Bate un redoble de manos', 'extremos', FALSE, TRUE),
('Bate el compás con los dedos', 'extremos', FALSE, TRUE),
('Bate el ritmo con una sonrisa', 'extremos', FALSE, TRUE),
('Alcanza una nota musical', 'extremos', FALSE, TRUE),
('Alcanza un tono estruendoso', 'extremos', FALSE, TRUE),
('Alcanza una posición de equilibrio', 'extremos', FALSE, TRUE),
('Alcanza un gesto de manos', 'extremos', FALSE, TRUE),
('Alcanza un salto pequeño', 'extremos', FALSE, TRUE),
('Muestra una posición de equilibrio', 'extremos', FALSE, TRUE),
('Muestra una fuerza con un objeto ligero', 'extremos', FALSE, TRUE),
('Muestra un gesto de confianza', 'extremos', FALSE, TRUE),
('Muestra una emoción divertida', 'extremos', FALSE, TRUE),
('Muestra una coordinación exagerada', 'extremos', FALSE, TRUE),
('Reparte los aplausos', 'extremos', FALSE, TRUE),
('Reparte un turno de canto', 'extremos', FALSE, TRUE),
('Reparte un papel de personaje', 'extremos', FALSE, TRUE),
('Reparte un turno de abrazos', 'extremos', FALSE, TRUE),
('Reparte una consigna de baile', 'extremos', FALSE, TRUE),
('Aplaude con ritmo', 'extremos', FALSE, TRUE),
('Aplaude a alguien con entusiasmo', 'extremos', FALSE, TRUE),
('Aplaude al final de una canción', 'extremos', FALSE, TRUE),
('Aplaude con las dos manos', 'extremos', FALSE, TRUE),
('Aplaude después de una actuación', 'extremos', FALSE, TRUE),
('Cambia de posición en el centro', 'extremos', FALSE, TRUE),
('Cambia de gesto al ritmo', 'extremos', FALSE, TRUE),
('Cambia de expresión durante la ronda', 'extremos', FALSE, TRUE),
('Cambia de postura en la foto', 'extremos', FALSE, TRUE),
('Cambia de estilo en la imitación', 'extremos', FALSE, TRUE),
('Pone un pie en el centro del círculo', 'extremos', FALSE, TRUE),
('Pone la voz al máximo', 'extremos', FALSE, TRUE),
('Haz una mirada de sorpresa y mantén la pose tres segundos', 'extremos', FALSE, TRUE),
('Pone una pose final', 'extremos', FALSE, TRUE),
('Pone el ritmo más fuerte', 'extremos', FALSE, TRUE)
ON DUPLICATE KEY UPDATE
    active = IF(@migration_applied = 0, TRUE, active),
    is_for_impostor = VALUES(is_for_impostor);

INSERT INTO migration_2026_host_tasks (migration_key)
VALUES ('2026_host_tasks')
ON DUPLICATE KEY UPDATE applied_at = applied_at;

SELECT challenge_type, COUNT(*) AS task_count
FROM tasks
WHERE active = TRUE
GROUP BY challenge_type
ORDER BY challenge_type;

SELECT COUNT(*) AS total_active_tasks
FROM tasks
WHERE active = TRUE;

SELECT challenge_type, description, COUNT(*) AS duplicate_count
FROM tasks
WHERE active = TRUE
GROUP BY challenge_type, description
HAVING COUNT(*) > 1;
